use_frameworks!

target 'OKTableViewLiaison_Example' do
    pod 'OKTableViewLiaison', :path => '../'
    
end

target 'OKTableViewLiaison_Tests' do
    pod 'OKTableViewLiaison', :path => '../'
    
end
