use_frameworks!
platform :ios, '9.0'

target 'OKTableViewLiaison_Example' do
    pod 'OKTableViewLiaison', :path => '../'
end

target 'OKTableViewLiaison_Tests' do
    pod 'OKTableViewLiaison', :path => '../'
end
